/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sistemainventario.Formularios;

import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import sistemainventario.*;
import sistemainventario.costos.CostoPEPS;

/**
 *
 * @author jeffe
 */
public class Almacen extends javax.swing.JFrame {

    /**
     * Creates new form Almacen
     */
    //Vector MyVproducto = new Vector(); //creare un vector de productos
    //  List MyListProduct = new ArrayList();
    List<CostoPEPS> costop = new ArrayList<>();
    int i = 0;
    int j = 0; //mostraremos los datos interados de cantidad y costo del primer datatable
    int k = 0;
    DefaultTableModel stock = new DefaultTableModel();
    DefaultTableModel facturas = new DefaultTableModel();
    DefaultTableModel Costeo = new DefaultTableModel();
    
    public Almacen() {
        
        initComponents();
        // aqui inicialiaza las columnas para stock table
        stock.addColumn("Codigo");
        stock.addColumn("Nombre");
        stock.addColumn("Cantidad");
        stock.addColumn("Costo");
        tablastock.setModel(stock);
        //aqui inicializa las columnas para factura
        facturas.addColumn("Numero de factura");
        facturas.addColumn("Cantidad");
        facturas.addColumn("Costo");
        tableFacturas.setModel(facturas);
        //aqui iniciliaza la columnas para mostrar datos de costeo
        Costeo.addColumn("Costo Venta");
        Costeo.addColumn("Utilidad");
        Costeo.addColumn("Costo Existencia");
        tableDatos.setModel(Costeo);
        //bloquear todos los componentes del area de stock menos los botones almacenar y facturar 
        txtCodigo.setEnabled(false);
        txtNombreProducto.setEnabled(false);
        txtNcompra.setEnabled(false);
        txtCantidadEntrada.setEnabled(false);
        txtCostoEntrada.setEnabled(false);
        txtCodigo.setEnabled(false);
        txtCodigo.setEnabled(false);
        BtnGuardarProdcuto.setEnabled(false);
        //bloquear todos los componentes del area de facturar menos los botones almacenar y facturar 
        txtFactura.setEnabled(false);
        txtcantidafactura.setEnabled(false);
        txtcostoFactura.setEnabled(false);
        BtnFactura.setEnabled(false);
        BtnBloquearStock.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSpinner1 = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txtCodigo = new javax.swing.JTextField();
        txtNombreProducto = new javax.swing.JTextField();
        txtCantidadEntrada = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNcompra = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtCostoEntrada = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        BtnGuardarProdcuto = new javax.swing.JButton();
        BtnFactura = new javax.swing.JButton();
        BtnBloquearStock = new javax.swing.JButton();
        BtnCostear = new javax.swing.JButton();
        BtnBloquearFactura = new javax.swing.JButton();
        BtnSalvar = new javax.swing.JButton();
        BtnSalvar1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableFacturas = new javax.swing.JTable();
        txtcantidafactura = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtFactura = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtcostoFactura = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablastock = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableDatos = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registro de Stock");

        jLabel1.setText("Código");

        jLabel2.setText("Nombre");

        txtNombreProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreProductoActionPerformed(evt);
            }
        });

        jLabel3.setText("No. Compra");

        jLabel4.setText("Cantidad");

        jLabel5.setText("Costo");

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, new java.awt.Color(204, 204, 204)));

        BtnGuardarProdcuto.setText("Agregar a stock");
        BtnGuardarProdcuto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGuardarProdcutoActionPerformed(evt);
            }
        });

        BtnFactura.setText("Facturar");
        BtnFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnFacturaActionPerformed(evt);
            }
        });

        BtnBloquearStock.setText("Vender");
        BtnBloquearStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBloquearStockActionPerformed(evt);
            }
        });

        BtnCostear.setText("Costear");
        BtnCostear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCostearActionPerformed(evt);
            }
        });

        BtnBloquearFactura.setText("Almacenar");
        BtnBloquearFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBloquearFacturaActionPerformed(evt);
            }
        });

        BtnSalvar.setText("Guardar informacion");

        BtnSalvar1.setText("Cargar informacion");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BtnGuardarProdcuto)
                .addGap(18, 18, 18)
                .addComponent(BtnFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnBloquearStock, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnCostear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnBloquearFactura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnSalvar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(22, 22, 22))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(BtnBloquearFactura)
                        .addGap(12, 12, 12)
                        .addComponent(BtnBloquearStock)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnCostear)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnSalvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                        .addComponent(BtnSalvar1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(BtnFactura, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                            .addComponent(BtnGuardarProdcuto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(26, 26, 26))
        );

        tableFacturas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableFacturas);

        jLabel6.setText("No. factura");

        jLabel7.setText("Cantidad");

        txtFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFacturaActionPerformed(evt);
            }
        });

        jLabel8.setText("Costo");

        tablastock.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tablastock);

        tableDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tableDatos);

        jLabel9.setText("Datos de inventario");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtcantidafactura, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(txtcostoFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(41, 41, 41)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCantidadEntrada, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtNcompra)
                                    .addComponent(txtCostoEntrada)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addGap(62, 62, 62)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNombreProducto)
                                    .addComponent(txtCodigo))))
                        .addGap(122, 122, 122)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtNombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtNcompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtCantidadEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtCostoEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtFactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtcantidafactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtcostoFactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreProductoActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtNombreProductoActionPerformed

    private void BtnGuardarProdcutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGuardarProdcutoActionPerformed
        //bloque para agregar
        //buscar la manera de validar que la lista este vacia
        //casos si esta vacia creo el objecto entrada y lo agrego a la lista costo pesp
        //caso que no este vacia son dos casos 
        //primero que id sea igual eso es agregacion
        //segundo que el id de la lista sea diferente al que crearemos

        //bloque a discutir 
        if (costop.isEmpty()) {//retorna true si esta vacia 
            //si esta vacia crea el objecto en la pos que se le indica caso inical pos 0
            Compras c1 = new Compras(txtNcompra, txtCantidadEntrada, txtCostoEntrada);
            costop.add(new CostoPEPS(txtCodigo, txtNombreProducto, c1));
        } else {
            
            costop.get(0).setMisCompras(new Compras(txtNcompra, txtCantidadEntrada, txtCostoEntrada));
            
        }
        //fin de bloque

        System.out.println(costop);
        //System.out.println(costop.get(j++));
        txtCodigo.setEnabled(false);
        txtNombreProducto.setEnabled(false);
        txtNcompra.setText(null);
        txtCantidadEntrada.setText(null);
        txtCostoEntrada.setText(null);
        //System.out.println(costop.get(i));

        // stock.setRowCount(0);
        //este ciclo manda al datatbale
        for (CostoPEPS costop1 : costop) {
            Object[] fila = {
                costop1.getCodigoArticulo(),
                costop1.getNombreArticulo(),
                //solventar el problema de indice
                costop1.getMisCompras().get(j).getCantidad(),
                costop1.getMisCompras().get(j).getCosto()
            
            };
            //nota para agregar mas productos solo debo buscar la manera de accerder a cierto indice en costo.getMIscompras ya sea agregando el for 
            //dentro de uno de los bloques de validacion

            stock.addRow(fila);
            j++; //next elemento de la lista mis compras
        }
        BtnBloquearStock.setEnabled(true);//habilitar las ventas

    }//GEN-LAST:event_BtnGuardarProdcutoActionPerformed

    private void BtnFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnFacturaActionPerformed
        
        //aqui agregaremos a la lista del producto la nuea factura que entra
        Ventas salida = new Ventas(txtFactura, txtcantidafactura, txtcostoFactura);
        costop.get(0).setMisVentas(salida);
        System.out.println(costop);
        // System.out.println(costop.get(0).costoVenta());
         for (CostoPEPS costop1 : costop) {
            Object[] fila = {
               
                //solventar el problema de indice
                costop1.getMisVentas().get(i).getNumeroFactura(),
                costop1.getMisVentas().get(i).getCantidad(),
                costop1.getMisVentas().get(i).getCostoFactura()
            
            };
            //nota para agregar mas productos solo debo buscar la manera de accerder a cierto indice en costo.getMIscompras ya sea agregando el for 
            //dentro de uno de los bloques de validacion

            facturas.addRow(fila);
            i++; //next elemento de la lista mis compras
        }
         txtFactura.setText(null);
         txtcantidafactura.setText(null);
         txtcostoFactura.setText(null);
    }//GEN-LAST:event_BtnFacturaActionPerformed

    private void txtFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFacturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFacturaActionPerformed

    private void BtnBloquearFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBloquearFacturaActionPerformed
        //habilitar la parte de almacenar
        txtCodigo.setEnabled(true);
        txtNombreProducto.setEnabled(true);
        txtNcompra.setEnabled(true);
        txtCantidadEntrada.setEnabled(true);
        txtCostoEntrada.setEnabled(true);
        txtCodigo.setEnabled(true);
        txtCodigo.setEnabled(true);
        BtnGuardarProdcuto.setEnabled(true);
        BtnBloquearFactura.setEnabled(false);
        //bloquear todos los componentes del area de facturar menos los botones almacenar y facturar 
        txtFactura.setEnabled(false);
        txtcantidafactura.setEnabled(false);
        txtcostoFactura.setEnabled(false);
        BtnFactura.setEnabled(false);
        

    }//GEN-LAST:event_BtnBloquearFacturaActionPerformed

    private void BtnBloquearStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBloquearStockActionPerformed
        // TODO add your handling code here:
        txtNcompra.setEnabled(false);
        txtCantidadEntrada.setEnabled(false);
        txtCostoEntrada.setEnabled(false);
        txtCodigo.setEnabled(false);
        txtCodigo.setEnabled(false);
        BtnGuardarProdcuto.setEnabled(false);
        BtnFactura.setEnabled(true);
        //habilitar almacenar
        txtFactura.setEnabled(true);
        txtcantidafactura.setEnabled(true);
        txtcostoFactura.setEnabled(true);
        BtnFactura.setEnabled(true);

    }//GEN-LAST:event_BtnBloquearStockActionPerformed

    private void BtnCostearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCostearActionPerformed
        // TODO add your handling code here:
      /*  System.out.print("EL costo venta es ");
        System.out.println(costop.get(0).costoVenta());
        System.out.print("EL costo existencia es ");
        System.out.println(costop.get(0).costoExistencia());
        System.out.print("la utilidad es ");
        System.out.println(costop.get(0).utilidad());*/
        //imprimire estas variables
       double CV=costop.get(0).costoVenta();
       double CE=costop.get(0).costoExistencia();
       double Utl=costop.get(0).utilidad();
            Object[] fila = {
               CV,
                CE,
                Utl
            
            };
            //nota para agregar mas productos solo debo buscar la manera de accerder a cierto indice en costo.getMIscompras ya sea agregando el for 
            //dentro de uno de los bloques de validacion

            Costeo.addRow(fila);
          //  i++; //next elemento de la lista mis compras
        
    }//GEN-LAST:event_BtnCostearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                    
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Almacen.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
            
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Almacen.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
            
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Almacen.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
            
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Almacen.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Almacen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBloquearFactura;
    private javax.swing.JButton BtnBloquearStock;
    private javax.swing.JButton BtnCostear;
    private javax.swing.JButton BtnFactura;
    private javax.swing.JButton BtnGuardarProdcuto;
    private javax.swing.JButton BtnSalvar;
    private javax.swing.JButton BtnSalvar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTable tablastock;
    private javax.swing.JTable tableDatos;
    private javax.swing.JTable tableFacturas;
    private javax.swing.JTextField txtCantidadEntrada;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtCostoEntrada;
    private javax.swing.JTextField txtFactura;
    private javax.swing.JTextField txtNcompra;
    private javax.swing.JTextField txtNombreProducto;
    private javax.swing.JTextField txtcantidafactura;
    private javax.swing.JTextField txtcostoFactura;
    // End of variables declaration//GEN-END:variables
}
